vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|07 May 2022 12:24:22 -0000
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|
vti_author:SR|UTTYN18-RYZENPC\\uttym
vti_modifiedby:SR|UTTYN18-RYZENPC\\uttym
vti_nexttolasttimemodified:TR|01 May 2022 07:48:03 -0000
vti_timecreated:TR|01 May 2022 07:39:27 -0000
vti_cacheddtm:TX|01 May 2022 07:48:19 -0000
vti_filesize:IR|127
vti_syncofs_sv52.star.ne.jp\:21/%2fsevemi.rin.ilnk.info/tannu:TW|07 May 2022 07:26:10 -0000
vti_syncwith_sv52.star.ne.jp\:21/%2fsevemi.rin.ilnk.info/tannu:TX|01 May 2022 07:48:19 -0000
